//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDePresentacion.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CapaDePresentacion.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap check {
            get {
                object obj = ResourceManager.GetObject("check", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap check20 {
            get {
                object obj = ResourceManager.GetObject("check20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a table.border {
        ///    border-collapse: collapse;
        ///}
        ///
        ///table.border th {
        ///    text-align: center;
        ///    padding: 5px;
        ///    border: 1px solid black;
        ///}
        ///
        ///table.border td {
        ///    text-align: center;
        ///    padding: 5px;
        ///    border: 1px solid black;
        ///}.
        /// </summary>
        internal static string DiseñoPlantillaCompra {
            get {
                return ResourceManager.GetString("DiseñoPlantillaCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a table.border {
        ///    border-collapse: collapse;
        ///}
        ///
        ///table.border th {
        ///    text-align: center;
        ///    padding: 5px;
        ///    border: 1px solid black;
        ///}
        ///
        ///table.border td {
        ///    text-align: center;
        ///    padding: 5px;
        ///    border: 1px solid black;
        ///}
        ///.
        /// </summary>
        internal static string DiseñoPlantillaVenta {
            get {
                return ResourceManager.GetString("DiseñoPlantillaVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///    &lt;title&gt;Compras&lt;/title&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; href=&quot;DiseñoPlantillaCompra.css&quot;&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;table border=&quot;0&quot; style=&quot;width:100%&quot;&gt;
        ///        &lt;tr&gt;
        ///
        ///            &lt;td style=&quot;width:15%&quot; valign=&quot;top&quot;&gt;&lt;/td&gt;
        ///            &lt;td style=&quot;width:60%&quot; valign=&quot;top&quot; align=&quot;center&quot;&gt;
        ///
        ///                &lt;label style=&quot;font-size:20px;font-weight:bold;margin-bottom:10p [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string PlantillaWebCompra {
            get {
                return ResourceManager.GetString("PlantillaWebCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///    &lt;title&gt;Venta&lt;/title&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; href=&quot;DiseñoPlantillaVenta.css&quot;&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;table border=&quot;0&quot; style=&quot;width:100%&quot;&gt;
        ///        &lt;tr&gt;
        ///
        ///            &lt;td style=&quot;width:15%&quot; valign=&quot;top&quot;&gt;&lt;/td&gt;
        ///            &lt;td style=&quot;width:60%&quot; valign=&quot;top&quot; align=&quot;center&quot;&gt;
        ///
        ///                &lt;label style=&quot;font-size:20px;font-weight:bold;margin-bottom:10px&quot;&gt; [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string PlantillaWebVenta {
            get {
                return ResourceManager.GetString("PlantillaWebVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngwing_com {
            get {
                object obj = ResourceManager.GetObject("pngwing.com", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap red_trash_can_icon {
            get {
                object obj = ResourceManager.GetObject("red_trash_can_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap trash20 {
            get {
                object obj = ResourceManager.GetObject("trash20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap trash25 {
            get {
                object obj = ResourceManager.GetObject("trash25", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap trash32 {
            get {
                object obj = ResourceManager.GetObject("trash32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
